---
desc: "Swifty DEMO functions"
files:
        - name: "Hello world"
          path: "functions/golang/helloworld.go"
          lang: "golang"
          desc: "A hello-world example"
        - name: "Simple Telegram chatbot"
          path: "functions/python/telegram_bot.py"
          lang: "python"
          desc: "Simple chatbot for Telegram."
        - name: "MongoDB integration"
          path: "functions/python/mongo.py"
          lang: "python"
          desc: "How to work with Mongo using Python."
        - name: "MariaDB integration"
          path: "functions/python/maria.py"
          lang: "python"
          desc: "How to work with Maria using Python."
        - name: "Hello world"
          path: "functions/python/helloworld.py"
          lang: "python"
          desc: "A hello-world example"
        - name: "Avatar management"
          path: "functions/python/sample-avatar-management.py"
          lang: "python"
          desc: "How to manage avatars: upload, download, delete, storing on S3."
        - name: "Profile management"
          path: "functions/golang/simple-profile-mgmt.go"
          lang: "golang"
          desc: "How to manage user profiles: create, update, delete, storing in Mongo."
        - name: "User management"
          path: "functions/golang/simple-user-mgmt.go"
          lang: "golang"
          desc: "Basic password-based auth for users."
        - name: "Facebook auth"
          path: "functions/golang/facebook-user-mgmt.go"
          lang: "golang"
          desc: "Helper for authenticating users via facebook"
        - name: "Facebook to Password-based accounts linking"
          path: "functions/golang/user-accounts-link.go"
          lang: "golang"
          desc: "Helper for linking facebook account with the one created via basic pwd-auth function"
        - name: "Task management function"
          path: "functions/python/todo-app.py"
          lang: "python"
          desc: "Sample TODO app with the ability to add/del, list and modify simple TODO entries"
        - name: "Authentication-as-a-Service"
          path: "swy-aaas.yaml"
          lang: "deployment"
          desc: "Authentication-as-a-Service with JWT tokens, Facebook auth and profile management"
        - name: "Serverless chat (with integrated auth)"
          path: "chat.yaml"
          lang: "deployment"
          desc: "Chat that uses websockets and integrated authentication"
        - name: "Serverless chat with websockets"
          path: "functions/golang/chat.go"
          lang: "golang"
          desc: "Chat that uses websockets"
        - name: "Backend for ToDo application"
          path: "todoapp.yaml"
          lang: "deployment"
          desc: "ToDo app with task, profile and avatar management"
